trigger:
  branches:
    include:
      - master
      - main
  paths:
    exclude:
      - .ci/*

variables:
  BUILD_NUMBER: 0.1.$(Build.BuildId)
  REACT_APP_BUILD_NUMBER: 0.1.$(Build.BuildId)
  solution: 'webapi/Seger.sln'
  project: 'webapi/src/Seger.App/Seger.App.csproj'

stages:
  - stage: Build
    jobs:
      - job: Build_Backend_Frontend
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - template: ./azure-pipelines-tests-shared.yml

          - script: |
              npm --no-git-tag-version version $(BUILD_NUMBER) --allow-same-version
            displayName: 'set version'

          - script: |
              yarn build-dotnet
            displayName: 'build backend'

          - script: |
              yarn build-frontend
              yarn copy-frontend
            displayName: 'build frontend'

#          - script: |
#              mkdir ./cobertura
#              find '$(Agent.TempDirectory)' -name 'coverage.cobertura.xml' -exec cp --backup=numbered -t ./cobertura {} +
#              cd ./cobertura
#              for f in *~*~; do mv "$f" "$(echo "$f" | sed -r 's/(.*)\.~([0-9]+)~/\2\1/')"; done;
#            displayName: 'copy coverage files'

#          - script: |
#              cd ./webapi
#              dotnet tool restore
#              dotnet reportgenerator -reports:../cobertura/* -targetdir:../cobertura/report -sourcedirs:./ -assemblyfilters:+Lmt.Unicorn.App\;+Lmt.Unicorn.Common\;+Lmt.Unicorn.Domain
#            displayName: 'generate coverage report'

#          - publish: './cobertura'
#            artifact: 'backend-coverage'

#          - task: PublishTestResults@2
#            inputs:
#              testResultsFormat: 'JUnit'
#              testResultsFiles: '**/junit.xml'
#              mergeTestResults: true

          - script: |
              docker login $(DOCKER_REGISTRY) -u $(DOCKER_USER) -p $(DOCKER_TOKEN)
            displayName: 'Authenticate at Container Registry'

          - task: Docker@2
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
            inputs:
              repository: $(DOCKER_REGISTRY)
              command: 'buildAndPush'
              Dockerfile: 'publish/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/publish'
              tags: |
                $(BUILD_NUMBER)
                latest
            displayName: 'build and push version+latest'

          - task: Docker@2
            condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
            inputs:
              repository: $(DOCKER_REGISTRY)
              command: 'buildAndPush'
              Dockerfile: 'publish/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/publish'
              tags: |
                $(BUILD_NUMBER)
            displayName: 'build and push version only'

          - publish: './docker-compose.yaml'
            artifact: 'docker-compose'

          - publish: './nginx'
            artifact: 'nginx'

          - publish: './scripts/deploy'
            artifact: 'scripts'

  - stage: DeployToDev
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment:
        environment:
          name: 'DEV'
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - template: scripts/azure-deploy-template.yml

  - stage: TagDevSources
    dependsOn: DeployToDev
    condition: succeeded()
    jobs:
      - job:
        condition: succeeded()
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            persistCredentials: true
          - script: |
              git tag 'dev' -f
              git push origin 'dev' -f --tags

  - stage: DeployToProd
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment:
        environment:
          name: 'PROD'
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - template: scripts/azure-deploy-template.yml

  - stage: TagProdSources
    dependsOn: DeployToProd
    condition: succeeded()
    jobs:
      - job:
        condition: succeeded()
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            persistCredentials: true
          - script: |
              git tag 'prod' -f
              git push origin 'prod' -f --tags
